# Kris' profile-aware `claude` wrapper — mounted straight into host k's
# configuration (the only consumer), not a shared flake.modules.darwin.* module.
#
# nix-darwin has no per-user xdg.configFile, so the generated zsh snippet — the
# host-specific rule/profile assignments prepended to the static wrapper.zsh —
# is built with writeText and linked into ~/.config/zsh during activation (the
# stowed ~/.config/zsh/.zshrc sources it when present). The desktop-app pin uses
# nix-darwin's launchd.user.agents.
{
  configurations.darwin.k.module =
    { lib, pkgs, ... }:
    let
      home = "/Users/k";
      # Host k's settings (formerly kriswill.claude-account-selector.* options,
      # hardcoded when the module became k-only). Profile `<name>` maps to
      # config dir ~/.claude-<name>; rules are path-prefix -> profile (longest
      # matching prefix wins, augmented at runtime by `claude pin`).
      defaultProfile = "me";
      profiles = [
        "me"
        "work"
      ];
      rules = {
        "${home}/src/perforce" = "work";
      };
      # Pin the GUI Claude desktop app to ~/.claude-me (GUI apps can't do the
      # per-$PWD switching the shell wrapper does). See README.md.
      desktopProfile = "me";

      # Pure-zsh "inputs" prepended to wrapper.zsh: well-known variable
      # assignments, NOT template interpolation. wrapper.zsh stays a
      # standalone-runnable file.
      rulePairs = lib.concatStringsSep " " (
        lib.mapAttrsToList (
          prefix: profile: "${lib.escapeShellArg prefix} ${lib.escapeShellArg profile}"
        ) rules
      );
      profileWords = lib.concatStringsSep " " (map lib.escapeShellArg profiles);
      generatedInputs = ''
        # --- generated by the claude-account-selector module (inputs for wrapper.zsh) ---
        _CCW_DEFAULT_PROFILE=${lib.escapeShellArg defaultProfile}
        _CCW_VALID_PROFILES=(${profileWords})
        typeset -gA _CCW_RULES=(${rulePairs})
      '';
      snippet = pkgs.writeText "claude-account-selector.zsh" (
        generatedInputs
        # Scrub a GUI-session desktop pin (see desktopProfile) so interactive shells
        # re-resolve by $PWD instead of inheriting it. Runs before wrapper.zsh, which
        # treats any non-empty CLAUDE_CONFIG_DIR as an explicit override. An explicit
        # `CLAUDE_CONFIG_DIR=… claude` (set after init) is unaffected and still wins.
        + ''
          [[ "$CLAUDE_CONFIG_DIR" == "$HOME/.claude-${desktopProfile}" ]] && unset CLAUDE_CONFIG_DIR
        ''
        + builtins.readFile ./wrapper.zsh
      );
    in
    {
      # ccglass (the LLM-traffic inspector the ccglass() wrapper invokes via
      # `command ccglass`) — provided by Nix instead of a global `bun -g i ccglass`.
      environment.systemPackages = [ pkgs.ccglass ];

      # Generate ~/.config/zsh/claude-account-selector.zsh and link it during
      # activation; the stowed .zshrc sources it when present. Order 1600:
      # after dotfiles-stow (1500). Run as the user so the link isn't
      # root-owned; ln -sfn keeps the store path current across rebuilds.
      system.activationScripts.postActivation.text = lib.mkOrder 1600 ''
        /usr/bin/sudo -u k --set-home /bin/sh -c \
          'mkdir -p ${home}/.config/zsh && ln -sfn ${snippet} ${home}/.config/zsh/claude-account-selector.zsh'
      '';

      # Pin the GUI desktop app to ~/.claude-<desktopProfile> by injecting
      # CLAUDE_CONFIG_DIR into the macOS login (Aqua) session at login.
      launchd.user.agents.claude-config-dir = {
        serviceConfig = {
          ProgramArguments = [
            "/bin/launchctl"
            "setenv"
            "CLAUDE_CONFIG_DIR"
            "${home}/.claude-${desktopProfile}"
          ];
          RunAtLoad = true;
        };
      };
    };
}
