{
  flake.modules.homeManager.claude-account-selector =
    { lib, config, ... }:
    let
      cfg = config.kriswill.claude-account-selector;
      # Pure-zsh "inputs" prepended to wrapper.zsh: well-known variable assignments,
      # NOT template interpolation. wrapper.zsh stays a standalone-runnable file.
      rulePairs =
        lib.concatStringsSep " " (
          lib.mapAttrsToList (prefix: profile: "${lib.escapeShellArg prefix} ${lib.escapeShellArg profile}") cfg.rules
        );
      profileWords = lib.concatStringsSep " " (map lib.escapeShellArg cfg.profiles);
      inputs = ''
        # --- generated by the claude-account-selector module (inputs for wrapper.zsh) ---
        _CCW_DEFAULT_PROFILE=${lib.escapeShellArg cfg.defaultProfile}
        _CCW_VALID_PROFILES=(${profileWords})
        typeset -gA _CCW_RULES=(${rulePairs})
      '';
    in
    {
      options.kriswill.claude-account-selector = {
        enable = lib.mkEnableOption "Kris' profile-aware claude wrapper (per-project account selection)";

        defaultProfile = lib.mkOption {
          type = lib.types.str;
          default = "me";
          description = "Profile used when no rule matches the current directory.";
        };

        profiles = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ "me" "work" ];
          description = ''
            Accepted profile names. Each `<name>` maps to config dir `~/.claude-<name>`
            and (optionally) keychain token item `claude-token-<name>`.
          '';
        };

        rules = lib.mkOption {
          type = lib.types.attrsOf lib.types.str;
          default = { "${config.home.homeDirectory}/src/perforce" = "work"; };
          example = lib.literalExpression ''
            {
              "/Users/k/src/perforce" = "work";
              "/Users/k/clients/acme" = "work";
            }
          '';
          description = ''
            Built-in path-prefix -> profile rules (longest matching prefix wins),
            augmented at runtime by `claude pin`. Set to `{ }` for no built-in mapping.
          '';
        };
      };

      config = lib.mkIf cfg.enable {
        programs.zsh.initContent = lib.mkAfter (inputs + builtins.readFile ./wrapper.zsh);
      };
    };
}
