# Kris' profile-aware `claude` wrapper (system-level port of the old
# home-manager module).
#
# nix-darwin has no per-user xdg.configFile, so the generated zsh snippet — the
# host-specific rule/profile assignments prepended to the static wrapper.zsh —
# is built with writeText and linked into ~/.config/zsh during activation (the
# stowed ~/.config/zsh/.zshrc sources it when present). The desktop-app pin uses
# nix-darwin's launchd.user.agents in place of home-manager's launchd.agents.
{
  flake.modules.darwin.claude-account-selector =
    {
      lib,
      config,
      pkgs,
      ...
    }:
    let
      home = "/Users/k";
      cfg = config.kriswill.claude-account-selector;
      # Pure-zsh "inputs" prepended to wrapper.zsh: well-known variable
      # assignments, NOT template interpolation. wrapper.zsh stays a
      # standalone-runnable file.
      rulePairs = lib.concatStringsSep " " (
        lib.mapAttrsToList (
          prefix: profile: "${lib.escapeShellArg prefix} ${lib.escapeShellArg profile}"
        ) cfg.rules
      );
      profileWords = lib.concatStringsSep " " (map lib.escapeShellArg cfg.profiles);
      generatedInputs = ''
        # --- generated by the claude-account-selector module (inputs for wrapper.zsh) ---
        _CCW_DEFAULT_PROFILE=${lib.escapeShellArg cfg.defaultProfile}
        _CCW_VALID_PROFILES=(${profileWords})
        typeset -gA _CCW_RULES=(${rulePairs})
      '';
      snippet = pkgs.writeText "claude-account-selector.zsh" (
        generatedInputs
        # Scrub a GUI-session desktop pin (see desktopProfile) so interactive shells
        # re-resolve by $PWD instead of inheriting it. Runs before wrapper.zsh, which
        # treats any non-empty CLAUDE_CONFIG_DIR as an explicit override. An explicit
        # `CLAUDE_CONFIG_DIR=… claude` (set after init) is unaffected and still wins.
        + lib.optionalString (cfg.desktopProfile != null) ''
          [[ "$CLAUDE_CONFIG_DIR" == "$HOME/.claude-${cfg.desktopProfile}" ]] && unset CLAUDE_CONFIG_DIR
        ''
        + builtins.readFile ./wrapper.zsh
      );
    in
    {
      options.kriswill.claude-account-selector = {
        enable = lib.mkEnableOption "Kris' profile-aware claude wrapper (per-project account selection)";

        defaultProfile = lib.mkOption {
          type = lib.types.str;
          default = "me";
          description = "Profile used when no rule matches the current directory.";
        };

        profiles = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [
            "me"
            "work"
          ];
          description = ''
            Accepted profile names. Each `<name>` maps to config dir `~/.claude-<name>`
            and (optionally) keychain token item `claude-token-<name>`.
          '';
        };

        rules = lib.mkOption {
          type = lib.types.attrsOf lib.types.str;
          default = {
            "${home}/src/work" = "work";
          };
          example = lib.literalExpression ''
            {
              "/Users/k/src/work" = "work";
              "/Users/k/clients/acme" = "work";
            }
          '';
          description = ''
            Built-in path-prefix -> profile rules (longest matching prefix wins),
            augmented at runtime by `claude pin`. Set to `{ }` for no built-in mapping.
          '';
        };

        desktopProfile = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = null;
          example = "me";
          description = ''
            Pin the GUI Claude **desktop app** (and its embedded Claude Code) to
            `~/.claude-<desktopProfile>`.

            GUI apps launched from Dock/Spotlight/Finder inherit the macOS launchd
            "Aqua" session environment, not your shell env — so the per-`$PWD` wrapper
            never runs for them and they otherwise fall back to the default `~/.claude`.
            When set, a per-user LaunchAgent runs `launchctl setenv CLAUDE_CONFIG_DIR
            ~/.claude-<desktopProfile>` at login so the desktop app picks it up.

            Because that value also leaks into every GUI-launched terminal (where the
            wrapper would treat it as an explicit override and skip `$PWD` resolution),
            a one-line scrub is prepended to the zsh init: interactive shells that merely
            *inherited* this exact value drop it, restoring per-`$PWD` switching. An
            explicit `CLAUDE_CONFIG_DIR=… claude` (set after init) still wins.

            Trade-off: the desktop app gets a single fixed profile — it cannot replicate
            the wrapper's per-directory me/work routing (there is no `$PWD` at GUI launch).
            `null` (default) leaves the desktop app on the unsegregated `~/.claude`.
          '';
        };
      };

      config = lib.mkIf cfg.enable (
        lib.mkMerge [
          {
            # ccglass (the LLM-traffic inspector the ccglass() wrapper invokes via
            # `command ccglass`) — provided by Nix instead of a global `bun -g i ccglass`.
            environment.systemPackages = [ pkgs.ccglass ];

            # Generate ~/.config/zsh/claude-account-selector.zsh and link it during
            # activation; the stowed .zshrc sources it when present. Order 1600:
            # after dotfiles-stow (1500). Run as the user so the link isn't
            # root-owned; ln -sfn keeps the store path current across rebuilds.
            system.activationScripts.postActivation.text = lib.mkOrder 1600 ''
              /usr/bin/sudo -u k --set-home /bin/sh -c \
                'mkdir -p ${home}/.config/zsh && ln -sfn ${snippet} ${home}/.config/zsh/claude-account-selector.zsh'
            '';
          }

          # Pin the GUI desktop app to ~/.claude-<desktopProfile> by injecting
          # CLAUDE_CONFIG_DIR into the macOS login (Aqua) session at login.
          (lib.mkIf (cfg.desktopProfile != null) {
            launchd.user.agents.claude-config-dir = {
              serviceConfig = {
                ProgramArguments = [
                  "/bin/launchctl"
                  "setenv"
                  "CLAUDE_CONFIG_DIR"
                  "${home}/.claude-${cfg.desktopProfile}"
                ];
                RunAtLoad = true;
              };
            };
          })
        ]
      );
    };
}
