{
  flake.modules.darwin.ghostty =
    { lib, pkgs, ... }:
    let
      # The macOS half of the shared ghostty config. The stowed config
      # (home/ghostty/.config/ghostty/config) ends with `config-file = ?os.conf`;
      # config-file includes load after the main file, so these keys get the
      # final word on OS-specific looks (window chrome, font size). Generated
      # here because the stow tree is shared verbatim with the NixOS hosts
      # (their half: modules/nixos/ghostty.nix).
      osConf = pkgs.writeText "ghostty-os.conf" ''
        # macOS half of the ghostty config — generated by modules/darwin/ghostty.nix.
        window-width = 141
        window-height = 45
        macos-titlebar-style = hidden
        font-size = 18
        keybind = global:cmd+grave_accent=toggle_quick_terminal
      '';
    in
    {
      homebrew.casks = [ "ghostty" ];
      environment.variables.TERMINFO_DIRS = [
        "/Applications/Ghostty.app/Contents/Resources/terminfo"
        "/usr/share/terminfo"
      ];

      # Symlink ghostty's terminfo to ~/.terminfo so it's discoverable before
      # TERMINFO_DIRS is set (fixes SSH sessions where the nix-darwin
      # set-environment script runs before env vars are exported). The app
      # bundle path lives outside the repo, so it can't be a stow file; the
      # ghostty config itself is stow-managed (home/ghostty/). Order 1600:
      # after dotfiles-stow (1500), run as the user.
      system.activationScripts.postActivation.text = lib.mkOrder 1600 ''
        /usr/bin/sudo -u k --set-home /bin/sh -c '
          /bin/ln -sfn \
            /Applications/Ghostty.app/Contents/Resources/terminfo /Users/k/.terminfo
          mkdir -p /Users/k/.config/ghostty
          /bin/ln -sfn ${osConf} /Users/k/.config/ghostty/os.conf
        '
      '';
    };
}
