-- Hyprland config for nebula — entry point.
--
-- The actual configuration is split by concept into sibling modules, required
-- below in load order. Hyprland resolves require() against ~/.config/hypr/, and
-- every file there is a symlink into the dotfiles stow tree
-- (home/hyprland/.config/hypr/). Edit the modules, then `hyprctl reload`.
--
-- Wiki: https://wiki.hypr.land/Configuring/Start/  (Lua hl.* API, 0.55+)
--
-- Module map:
--   monitors      — display layout (hl.monitor)
--   programs      — terminal/file-manager/menu (shared table, used by keybindings)
--   autostart     — hl.on("hyprland.start", …)
--   environment   — env vars, XWayland scaling, permissions
--   look-and-feel — general/decoration/layouts/misc (hl.config)
--   animations    — bezier/spring curves + per-leaf animations
--   input         — keyboard/touchpad/gestures/devices
--   keybindings   — all binds (requires "programs")
--   window-rules  — window + layer rules

require("monitors")
require("autostart")
require("environment")
require("look-and-feel")
require("animations")
require("input")
require("keybindings")
require("window-rules")

-- Noctalia color template — load LAST so its hl.config border colors win over
-- look-and-feel.lua. noctalia.lua is GENERATED by the Noctalia shell (not tracked
-- in this repo), so it can legitimately be absent: fresh setup, shell disabled, or
-- never run. require() on a missing module is a hard error that would break the
-- WHOLE config (this is the failure that blanked the OLED on a bad reload), so gate
-- it two ways:
--   * enableNoctalia — flip to false to opt out entirely;
--   * package.searchpath — resolves "noctalia" exactly like require would (Hyprland
--     sets package.path to ~/.config/hypr/?.lua), returning the file path if present
--     or nil if not, so an absent file is skipped cleanly instead of erroring.
-- (Live introspection, if you ever want it: package.loaded.noctalia is true once the
-- module has actually been required this session.)
local enableNoctalia = true

if enableNoctalia and package.searchpath("noctalia", package.path) then
  require("noctalia").apply_theme()
end

-- Our tweaks on top of noctalia's generated theme — must load LAST so they win.
require("noctalia-overrides")
