# Compiled (not shell-scripted) mount helper for the UNAS Pro 4 SMB share —
# see main.rs for why it's a Mach-O binary rather than a script. No external
# crates (pure std), so a bare rustc invocation rather than
# rustPlatform.buildRustPackage's Cargo.lock machinery.
#
# Two outputs in one derivation:
#   $out/bin/nas-mount              — the CLI, what launchd actually execs
#   $out/Applications/NasMount.app  — a real .app bundle wrapping that binary
#
# The .app exists solely to fix System Settings > Login Items attribution:
# a bare launchd agent has nothing for TCC to attribute, so it reads
# "Item from unidentified developer" no matter how well its executable is
# signed. Apple's documented answer (DTS, developer.apple.com/forums/thread/721918)
# is to point the plist's AssociatedBundleIdentifiers at a real, signed app
# bundle — which is also what supplies the custom icon. See
# knowledge/decisions/nas-mount-codesigning.md.
#
# nas-mount.icns is generated by make-icon.swift (checked in beside it,
# rendered from an SF Symbol); regenerate with:
#   swift make-icon.swift out.iconset && iconutil -c icns out.iconset
{
  stdenv,
  rustc,
  rcodesign,
  bundleId ? "net.kris.nas-mount",
}:
stdenv.mkDerivation {
  pname = "nas-mount";
  version = "0.1.0";
  dontUnpack = true;
  # rcodesign ad-hoc signs the finished bundle (see postInstall). It's pure
  # Rust and never touches the Keychain, so unlike Apple's `codesign` it works
  # inside the nix build sandbox.
  nativeBuildInputs = [
    rustc
    rcodesign
  ];

  buildPhase = ''
    runHook preBuild
    rustc -O -o nas-mount ${./main.rs}
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp nas-mount $out/bin/nas-mount

    app=$out/Applications/NasMount.app
    mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
    cp nas-mount "$app/Contents/MacOS/nas-mount"
    cp ${./nas-mount.icns} "$app/Contents/Resources/nas-mount.icns"

    cat > "$app/Contents/Info.plist" <<EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
      <key>CFBundleIdentifier</key>       <string>${bundleId}</string>
      <key>CFBundleName</key>             <string>NasMount</string>
      <key>CFBundleDisplayName</key>      <string>NAS Mount</string>
      <key>CFBundleExecutable</key>       <string>nas-mount</string>
      <key>CFBundleIconFile</key>         <string>nas-mount</string>
      <key>CFBundlePackageType</key>      <string>APPL</string>
      <key>CFBundleShortVersionString</key> <string>0.1.0</string>
      <key>CFBundleVersion</key>          <string>0.1.0</string>
      <key>LSMinimumSystemVersion</key>   <string>13.0</string>
      <!-- Background-only: never shows a Dock tile or menu bar. -->
      <key>LSUIElement</key>              <true/>
    </dict>
    </plist>
    EOF
    runHook postInstall
  '';

  # Ad-hoc sign the *bundle*. Not optional: rustc's linker ad-hoc signs the
  # standalone Mach-O, but that signature has no sealed Info.plist or
  # _CodeSignature/, so the enclosing .app is an invalid code object
  # ("code has no resources but signature indicates they must be present")
  # and launchd refuses to spawn it — `last exit code = 78: EX_CONFIG`, with
  # nothing in the job's own log because it never runs. A real Developer ID
  # signature can be layered on top later (scripts/sign-launchd-agents.ts);
  # this just guarantees the bundle is valid on any machine, cert or no cert.
  #
  # postFixup, not postInstall: fixupPhase strips binaries, which would
  # invalidate a signature applied during install.
  postFixup = ''
    rcodesign sign $out/Applications/NasMount.app
  '';

  meta = {
    description = "Mounts the UNAS Pro 4 Personal-Drive SMB share if not already mounted";
    mainProgram = "nas-mount";
    platforms = [
      "aarch64-darwin"
      "x86_64-darwin"
    ];
  };
}
