#!/usr/bin/env bash

# 1. on Mac
# brew install gnupg gpg-agent pinentry-mac

# 2. 1password - copy files to ~/.gnupg:
#   kris-public-gpg.key
#   kris-secret-gpg.key
#   kris-ownertrust-gpg.txt

# 3. import the keys
#   gpg --import kris-secret-gpg.key
#   gpg --import-ownertrust kris-ownertrust-gpg.txt

# 4. create some files:
#   ~/.gnupg/gpg.conf:
#   use-agent
# ---
#   ~/.gnupg/gpg-agent.conf
#   use-standard-socket
#   pinentry-program /usr/local/bin/pinentry-mac

# 5. get public key:
# gpg --list-secret-keys --keyid-format LONG

# #. make sure to configure your public key on GitHub:
# https://github.com/blog/2144-gpg-signature-verification

if [ -f ~/.gnupg/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
    source ~/.gnupg/.gpg-agent-info
    export GPG_AGENT_INFO
else
    eval $(gpg-agent --daemon --write-env-file ~/.gnupg/.gpg-agent-info)
fi