# DENDRITIC WRAPPER: the generated module body is held under
# `configurations.nixos.nebula.module` so this file is a valid flake-parts module
# (every `.nix` under modules/ is auto-imported as one). If you ever regenerate
# this with `nixos-generate-config`, re-apply this two-line wrapper around the
# raw output, or flake-parts evaluation will fail on the bare NixOS module.
{
  configurations.nixos.nebula.module =
    # Do not modify the generated body below!  It was generated by
    # ‘nixos-generate-config’ and may be overwritten by future invocations.
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:

    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "thunderbolt"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    }

  ;
}
