return {
  "brenoprata10/nvim-highlight-colors",
  lazy = false,
  opts = {
    enable_tailwind = true,
    render = "virtual",
    exclude_buffer = function(bufnr) return vim.fn.getfsize(vim.api.nvim_buf_get_name(bufnr)) > 1000000 end,
    custom_colors = {
      -- EFG Primary Colors
      { label = "primary%.enabled", color = "#FF4300" },
      { label = "primary%.focused", color = "#FF592B" },
      { label = "primary%.hover", color = "#FF592B" },
      { label = "primary%.active", color = "#FF7256" },
      { label = "primary%.highEmphasis", color = "#FF4300" },
      { label = "primary%.mediumEmphasis", color = "#FF4300" },
      { label = "primary%.lowEmphasis", color = "#FF4300" },

      -- EFG Secondary Colors
      { label = "secondary%.enabled", color = "#383838" },
      { label = "secondary%.focused", color = "#5D5D5D" },
      { label = "secondary%.hover", color = "#5D5D5D" },
      { label = "secondary%.active", color = "#828282" },
      { label = "secondary%.highEmphasis", color = "#383838" },
      { label = "secondary%.mediumEmphasis", color = "#383838" },
      { label = "secondary%.lowEmphasis", color = "#383838" },

      -- EFG Premium Colors
      { label = "premium%.enabled", color = "#D2FE00" },
      { label = "premium%.focused", color = "#E7FF2B" },
      { label = "premium%.hover", color = "#E7FF2B" },
      { label = "premium%.active", color = "#F7FF56" },
      { label = "premium%.highEmphasis", color = "#D2FE00" },
      { label = "premium%.mediumEmphasis", color = "#D2FE00" },
      { label = "premium%.lowEmphasis", color = "#D2FE00" },

      -- EFG Alert Colors
      { label = "alert%.enabled", color = "#EF0000" },
      { label = "alert%.focused", color = "#FF2B2B" },
      { label = "alert%.hover", color = "#FF2B2B" },
      { label = "alert%.active", color = "#FF5656" },
      { label = "alert%.highEmphasis", color = "#EF0000" },
      { label = "alert%.mediumEmphasis", color = "#EF0000" },
      { label = "alert%.lowEmphasis", color = "#EF0000" },

      -- EFG Common Colors
      { label = "common%.caution", color = "#FFC700" },
      { label = "common%.win", color = "#05FF00" },
      { label = "common%.info", color = "#00A3FF" },
      { label = "common%.success", color = "#05FF00" },
      { label = "common%.error", color = "#EF0000" },
      { label = "common%.loss", color = "#EF0000" },
      { label = "common%.draw", color = "#F1F1F1" },

      -- EFG Black Colors
      { label = "black%.full", color = "#060606" },
      { label = "black%.highEmphasis", color = "#060606" },
      { label = "black%.mediumEmphasis", color = "#060606" },
      { label = "black%.lowEmphasis", color = "#060606" },
      { label = "black%.disabled", color = "#060606" },

      -- EFG White Colors
      { label = "white%.full", color = "#F1F1F1" },
      { label = "white%.highEmphasis", color = "#CCCCCC" },
      { label = "white%.mediumEmphasis", color = "#A7A7A7" },
      { label = "white%.lowEmphasis", color = "#5D5D5D" },
      { label = "white%.disabled", color = "#383838" },

      -- EFG Theme Colors
      { label = "theme%.base", color = "#1D1D1D" },
      { label = "theme%.body", color = "#121212" },
      { label = "theme%.canvas", color = "#060606" },
      { label = "theme%.alt1", color = "#242424" },
      { label = "theme%.alt2", color = "#2E2E2E" },
      { label = "theme%.online", color = "#05FF00" },

      -- EFG Custom Colors
      { label = "activeGreen0", color = "#D6FFD6" },
      { label = "activeGreen10", color = "#ABFFAB" },
      { label = "activeGreen20", color = "#81FF81" },
      { label = "activeGreen30", color = "#56FF56" },
      { label = "activeGreen40", color = "#2BFF2B" },
      { label = "activeGreen50", color = "#05FF00" },
      { label = "activeGreen60", color = "#04E000" },
      { label = "activeGreen70", color = "#04C200" },
      { label = "activeGreen80", color = "#03A300" },
      { label = "activeGreen90", color = "#038500" },
      { label = "activeGreen100", color = "#026600" },
      { label = "amber0", color = "#FFFFD6" },
      { label = "amber10", color = "#FFFFAB" },
      { label = "amber20", color = "#FFF981" },
      { label = "amber30", color = "#FFED56" },
      { label = "amber40", color = "#FFDC2B" },
      { label = "amber50", color = "#FFC700" },
      { label = "amber60", color = "#E0AF00" },
      { label = "amber70", color = "#C29700" },
      { label = "amber80", color = "#A37F00" },
      { label = "amber90", color = "#856800" },
      { label = "amber100", color = "#665000" },
      { label = "blue0", color = "#D6F6FF" },
      { label = "blue10", color = "#ABEAFF" },
      { label = "blue20", color = "#81DCFF" },
      { label = "blue30", color = "#56CBFF" },
      { label = "blue40", color = "#2BB8FF" },
      { label = "blue50", color = "#00A3FF" },
      { label = "blue60", color = "#008FE0" },
      { label = "blue70", color = "#007CC2" },
      { label = "blue80", color = "#0068A3" },
      { label = "blue90", color = "#005585" },
      { label = "blue100", color = "#004166" },
      { label = "cyan0", color = "#D6FFFF" },
      { label = "cyan10", color = "#ABFFFF" },
      { label = "cyan20", color = "#81FFFF" },
      { label = "cyan30", color = "#56FFF6" },
      { label = "cyan40", color = "#2BFFE6" },
      { label = "cyan50", color = "#00FFD1" },
      { label = "cyan60", color = "#00E0B8" },
      { label = "cyan70", color = "#00C29F" },
      { label = "cyan80", color = "#00A386" },
      { label = "cyan90", color = "#00856D" },
      { label = "cyan100", color = "#006654" },
      { label = "gray0", color = "#F1F1F1" },
      { label = "gray10", color = "#CCCCCC" },
      { label = "gray20", color = "#A7A7A7" },
      { label = "gray30", color = "#828282" },
      { label = "gray40", color = "#5D5D5D" },
      { label = "gray50", color = "#383838" },
      { label = "gray60", color = "#2E2E2E" },
      { label = "gray70", color = "#242424" },
      { label = "gray80", color = "#1D1D1D" },
      { label = "gray90", color = "#121212" },
      { label = "gray95", color = "#0C0C0C" },
      { label = "gray100", color = "#060606" },
      { label = "gray200", color = "#A0A0A0" },
      { label = "heatedGreen0", color = "#FBFFD6" },
      { label = "heatedGreen10", color = "#F2FFAB" },
      { label = "heatedGreen20", color = "#E6FF81" },
      { label = "heatedGreen30", color = "#D6F356" },
      { label = "heatedGreen40", color = "#C1E02C" },
      { label = "heatedGreen50", color = "#A9C813" },
      { label = "heatedGreen60", color = "#95B011" },
      { label = "heatedGreen70", color = "#80980E" },
      { label = "heatedGreen80", color = "#6C800C" },
      { label = "heatedGreen90", color = "#58680A" },
      { label = "heatedGreen100", color = "#445008" },
      { label = "heatedOrange0", color = "#FFD6D6" },
      { label = "heatedOrange10", color = "#FFABAB" },
      { label = "heatedOrange20", color = "#FF8181" },
      { label = "heatedOrange30", color = "#FF5656" },
      { label = "heatedOrange40", color = "#FF2B2B" },
      { label = "heatedOrange50", color = "#EF0000" },
      { label = "heatedOrange60", color = "#D20000" },
      { label = "heatedOrange70", color = "#B60000" },
      { label = "heatedOrange80", color = "#990000" },
      { label = "heatedOrange90", color = "#7C0000" },
      { label = "heatedOrange100", color = "#600000" },
      { label = "orange0", color = "#FFD7D6" },
      { label = "orange10", color = "#FFB2AB" },
      { label = "orange20", color = "#FF9081" },
      { label = "orange30", color = "#FF7256" },
      { label = "orange40", color = "#FF592B" },
      { label = "orange50", color = "#FF4300" },
      { label = "orange60", color = "#E03B00" },
      { label = "orange70", color = "#C23300" },
      { label = "orange80", color = "#A32B00" },
      { label = "orange90", color = "#852300" },
      { label = "orange100", color = "#661B00" },
      { label = "purple0", color = "#FFD6FF" },
      { label = "purple10", color = "#FFABFF" },
      { label = "purple20", color = "#FF81FF" },
      { label = "purple30", color = "#FF56FF" },
      { label = "purple40", color = "#FF2BFF" },
      { label = "purple50", color = "#FA00FF" },
      { label = "purple60", color = "#DC00E0" },
      { label = "purple70", color = "#BE00C2" },
      { label = "purple80", color = "#A000A3" },
      { label = "purple90", color = "#820085" },
      { label = "purple100", color = "#640066" },
      { label = "victoryGreen0", color = "#FFFFD6" },
      { label = "victoryGreen10", color = "#FFFFAB" },
      { label = "victoryGreen20", color = "#FFFF81" },
      { label = "victoryGreen30", color = "#F7FF56" },
      { label = "victoryGreen40", color = "#E7FF2B" },
      { label = "victoryGreen50", color = "#D2FE00" },
      { label = "victoryGreen60", color = "#B9E000" },
      { label = "victoryGreen70", color = "#A0C100" },
      { label = "victoryGreen80", color = "#86A300" },
      { label = "victoryGreen90", color = "#6D8400" },
      { label = "victoryGreen100", color = "#546600" },
    },
  },
}
