# ~/.config/zsh/.zshrc — Kris' interactive zsh config (ZDOTDIR = ~/.config/zsh).
#
# Deployed by the stow tree (home/zsh) via each OS's dotfiles-stow module
# (modules/darwin/dotfiles-stow.nix, modules/nixos/dotfiles-stow.nix). The
# system /etc/zshenv sets ZDOTDIR here (each OS's zsh module), and /etc/zshrc
# provides compinit, autosuggestions, and syntax highlighting. This file runs
# last, so it gets the final word on aliases and the prompt.
#
# Core shell behavior (history, options, keymap, PATH) lives here; everything
# else is broken out into sibling files sourced below. Source order matters —
# see the comment on each source line.

## History — the system /etc/zshrc already set HISTSIZE/SAVEHIST/HISTFILE
## (~/.local/state/zsh/history); raise the limits here.
HISTSIZE=100000
# shellcheck disable=SC2034 # SAVEHIST is a zsh parameter; shellcheck only knows bash
SAVEHIST=10000000

## Options
setopt interactivecomments # allow comments on the command line
setopt AUTO_CD             # bare `dir/` cd's into it

## Editor — used by edit-command-line below (EDITOR/MANPAGER are set
## system-wide by each OS's neovim module).
export VISUAL=nvim

## Vi-mode + edit-command-line: press `v` in command mode to edit the current
## line in $VISUAL.
set -o vi
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

## Aliases and their completions.
source "$ZDOTDIR/aliases.zsh"

## `y` — yazi wrapper that cd's into yazi's last dir (pure POSIX sh, so other
## POSIX shells can share the same file).
source "$ZDOTDIR/yazi.sh"

## Opt-in helper functions (stderred).
source "$ZDOTDIR/functions.zsh"

## Darwin-specific setup — self-guarded, no-op elsewhere. Must precede the
## PATH export below (brew shellenv prepends its own paths).
source "$ZDOTDIR/darwin.zsh"

## PATH: bun globals and user-local bins, plus the persistent system-profile path
## as a fallback. On macOS, set-environment puts /run/current-system/sw/bin on
## PATH, but that symlink lives in volatile /run and is only recreated by the
## activate-system daemon once the FileVault-encrypted /nix volume mounts at login
## — so a terminal opened in that brief post-login window can't find
## starship/zoxide/direnv/etc. /nix/var/nix/profiles/system/sw/bin is the same
## store path and resolves the moment /nix is mounted, independent of /run.
## (Harmless on NixOS, where /run/current-system is reliable.)
export PATH="$HOME/.bun/bin:$HOME/.local/bin:$PATH:/nix/var/nix/profiles/system/sw/bin"

## Third-party tool hooks: starship prompt, zoxide, direnv, fzf, hstr. Must
## follow the PATH export above so the tools are findable.
source "$ZDOTDIR/integrations.zsh"

## claude-account-selector wrapper — generated by its darwin module on
## hosts that enable it; absent elsewhere.
[ -f "$ZDOTDIR/claude-account-selector.zsh" ] && source "$ZDOTDIR/claude-account-selector.zsh"
