# ~/.config/zsh/.zshrc — Kris' interactive zsh config (ZDOTDIR = ~/.config/zsh).
#
# Deployed by the stow tree (home/zsh) via modules/darwin/dotfiles-stow.nix.
# nix-darwin's /etc/zshenv sets ZDOTDIR here (modules/darwin/zsh.nix), and
# /etc/zshrc provides compinit, autosuggestions, and syntax highlighting. This
# file runs last, so it gets the final word on aliases and the prompt.

## History — /etc/zshrc (nix-darwin) already set HISTSIZE/SAVEHIST/HISTFILE
## (~/.local/state/zsh/history); raise the limits here.
HISTSIZE=100000
SAVEHIST=10000000

## Options
setopt interactivecomments # allow comments on the command line
setopt AUTO_CD             # bare `dir/` cd's into it

## Session variables from the remaining home-manager modules. home-manager's
## zsh integration is gone, so source its env file directly (stable path with
## home-manager.useUserPackages).
[ -f /etc/profiles/per-user/k/etc/profile.d/hm-session-vars.sh ] &&
  source /etc/profiles/per-user/k/etc/profile.d/hm-session-vars.sh

## Editor — used by edit-command-line below (EDITOR/MANPAGER are set
## system-wide by modules/darwin/neovim.nix).
export VISUAL=nvim

## Vi-mode + edit-command-line: press `v` in command mode to edit the current
## line in $VISUAL.
set -o vi
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

## Aliases. ls -> eza; the ls-family aliases chain off it (zsh re-expands the
## first word, so e.g. `ll` -> `ls -lhF` -> `eza --icons --hyperlink -lhF`).
alias ls='eza --icons --hyperlink'
alias ld='ls -D'
alias ll='ls -lhF'
alias la='ls -lahF'
alias l='la'
alias t="ls -T -I '.git'"
alias cat='bat'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias man='batman'
alias ff='fastfetch'
alias gv='NVIM_APPNAME=gman nvim'
alias claude-yolo='claude --dangerously-skip-permissions'
alias cyolo='claude --dangerously-skip-permissions'

## Git (gco/gba chain off g the same way the ls family chains off ls).
alias g='git'
alias gco='g checkout'
alias gba='g branch -a'
alias lg='lazygit'

## man-page completion for bat-extras' `batman`.
compdef batman=man

## Red background on stderr. Defined but not enabled by default — run `stderred`
## to turn it on in the current shell.
function stderred() {
  local RED_BG=$'\e[41m' RESET=$'\e[0m'
  function colorize_stderr() {
    while IFS= read -r line; do
      printf '%s%s%s\n' "$RED_BG" "$line" "$RESET"
    done
  }
  exec 2> >(colorize_stderr)
}

## Darwin-specific (guarded so this file stays portable across hosts).
## determinate-nixd's `completion zsh` takes ~300ms per shell to emit the same
## static script, so cache it and refresh only when the binary changes.
if command -v determinate-nixd >/dev/null; then
  _dnd_bin="$(command -v determinate-nixd)"
  _dnd_cache="$ZDOTDIR/.determinate-nixd-completion.zsh"
  if [[ ! -f "$_dnd_cache" || "$_dnd_bin" -nt "$_dnd_cache" ]]; then
    "$_dnd_bin" completion zsh >"$_dnd_cache"
  fi
  source "$_dnd_cache"
  unset _dnd_bin _dnd_cache
fi
[ -x /opt/homebrew/bin/brew ] && eval "$(/opt/homebrew/bin/brew shellenv)"

## PATH: bun globals and user-local bins.
export PATH="$HOME/.bun/bin:$HOME/.local/bin:$PATH"

## Integrations formerly injected by home-manager's programs.zsh.
## Prompt — starship (nix-darwin's default `prompt suse` is disabled in
## modules/darwin/zsh.nix so this wins cleanly).
eval "$(starship init zsh)"

## Smart cd — zoxide, jump with `j <dir>`.
eval "$(zoxide init zsh --cmd j)"

## direnv — per-directory envs.
eval "$(direnv hook zsh)"

## fzf keybindings + completion (binds Ctrl-R; hstr below must come AFTER so
## its Ctrl-R wins, matching the old home-manager init order).
source <(fzf --zsh)

## hstr — fuzzy history picker on Ctrl-R.
export HSTR_CONFIG=hicolor
setopt histignorespace
bindkey -s "\C-r" "\C-a hstr -- \C-j"

## claude-account-selector wrapper — generated by its home-manager module on
## hosts that enable it; absent elsewhere.
[ -f "$ZDOTDIR/claude-account-selector.zsh" ] && source "$ZDOTDIR/claude-account-selector.zsh"
