# Ghostty terminal — the NixOS twin of modules/darwin/ghostty.nix (install via
# the upstream programs.ghostty module; darwin uses a Homebrew cask).
#
# os.conf: the Linux half of the shared ghostty config. The stowed config
# (home/ghostty/.config/ghostty/config) ends with `config-file = ?os.conf`;
# config-file includes load after the main file, so these keys get the final
# word on OS-specific looks (GTK window chrome, Hyprland integration, theme).
{
  flake.modules.nixos.ghostty =
    { pkgs, ... }:
    let
      user = "k";
      home = "/home/k";
      osConf = pkgs.writeText "ghostty-os.conf" ''
        # Linux half of the ghostty config — generated by modules/nixos/ghostty.nix.

        # Let Hyprland own window corner rounding (decoration.rounding in
        # home/hyprland look-and-feel.lua). corners.css (stow-managed, sits
        # beside this file) flattens ghostty's own libadwaita CSD corners so
        # there's a single source of truth for the radius.
        gtk-custom-css = ${home}/.config/ghostty/corners.css

        # Derive the libadwaita window theme from ghostty's own colors instead
        # of the system accent, so the (transparent) focused window doesn't pick
        # up a blue accent tint. Pairs with the background override in corners.css.
        window-theme = ghostty

        # Don't prompt "close this terminal?" when the compositor closes the
        # window (e.g. Hyprland SUPER+W / killactive). tmux already persists
        # sessions, so the confirmation is just friction.
        confirm-close-surface = false

        # No titlebar/decorations — tmux owns the chrome (status bar etc.) and
        # Hyprland handles window management. Title is still reported to the
        # compositor (see tmux set-titles) so other surfaces can show what's
        # active.
        window-decoration = none

        # Neutral almost-black (was #181616 warm / #101014 cool-navy) + noctalia
        # theme override (generated into ~/.config/ghostty/themes by noctalia).
        background = #0e0e0e
        background-opacity = 0.92

        # 150% of ghostty's default 12pt.
        font-size = 14
        theme = noctalia
      '';
    in
    {
      programs.ghostty.enable = true;

      systemd.tmpfiles.rules = [
        "d ${home}/.config/ghostty 0755 ${user} users - -"
        "L+ ${home}/.config/ghostty/os.conf - - - - ${osConf}"
      ];
    };
}
