export NICE_HOSTNAME=`hostname -f`
export SHORT_HOST=`hostname -s`

test -s ~/.bash_local && . $_
test -f ~/.config/bash/exports && . $_
test -f ~/.config/bash/colors && . $_
test -f ~/.config/git/gitrc && . $_
test -f ~/.config/bash/aliases && . $_
test -f ~/.config/bash/prompt && . $_
test -f ~/.config/bash/save-directory && . $_

# readline settings
bind "set completion-ignore-case on"
bind "set bell-style none" # No bell, because it's damn annoying
bind "set show-all-if-ambiguous On" # this allows you to automatically show completion without double tab-ing

shopt -s checkwinsize
shopt -s histappend # make bash append to ~/.bash_history file
shopt -s globstar 2>/dev/null # Bash 4 and above only

if [ $SYSTEM_NAME = 'Linux' ]; then
  # NVM - Node Version Manager
  test -s ~/.nvm/nvm.sh && . $_
fi

if [ $SYSTEM_NAME = 'Darwin' ]; then
  test -s ~/.config/bash/terminal && . $_
  # set Docker environment variables using docker-machine
  # brew install nvm
  test -s $(brew --prefix nvm)/nvm.sh && . $_
  # brew install bash-completion
  test -s $(brew --prefix)/etc/bash_completion && . $_

  # java version switcher
  if which jenv > /dev/null; then eval "$(jenv init -)"; fi
fi

# RBENV - Alternate to RVM
# if type rbenv | grep -q '^function$' >/dev/null 2>&1; then
eval "$(rbenv init -)"
test -s ~/.travis/travis.sh && . $_
# fi

# setup bash completions
# install these from https://github.com/Homebrew/homebrew-completions
# ex brew install
if [ -s ~/.config/git/git-completion ]; then
   . ~/.config/git/git-completion
   # add git completion to aliases
   __git_complete g __git_main
   __git_complete gco _git_checkout
fi
complete -C ~/.config/ruby/rake-completion.rb -o default rake
complete -F _docker d
complete -F _docker_compose dc
complete -F _docker_machine dm
test -s ~/.config/bash/autojump/autojump.bash && . $_

# run bashrc if present
test -f ~/.bashrc && . $_
