[[ -s ~/.bash_local ]] && source ~/.bash_local


source ~/.config/bash/exports
source ~/.config/bash/colors
source ~/.config/git/gitrc
source ~/.config/bash/aliases
source ~/.config/bash/prompt
source ~/.config/bash/save-directory
source ~/.config/bash/virtualenvs-python
source ~/.config/git/git-completion

[[ -s ~/.bash_local ]] && source ~/.bash_local 

[ $SYSTEM_NAME == 'Darwin' ] && source ~/.config/bash/terminal
[[ -s /etc/bash_completion ]] && source /etc/bash_completion

# readline settings
bind "set completion-ignore-case on" 
bind "set bell-style none" # No bell, because it's damn annoying
bind "set show-all-if-ambiguous On" # this allows you to automatically show completion without double tab-ing

shopt -s checkwinsize
shopt -s histappend
shopt -s globstar 2>/dev/null # Bash 4 and above only

complete -C ~/.config/ruby/rake-completion.rb -o default rake

# RVM - Ruby Version Manager
[[ -s ~/.rvm/scripts/rvm ]] && source ~/.rvm/scripts/rvm
[[ -r $rvm_path/scripts/completion ]] && source $rvm_path/scripts/completion

# NVM - Node Version Manager
[[ -s ~/.nvm/nvm.sh ]] && source ~/.nvm/nvm.sh

if [ $SYSTEM_NAME = 'Darwin' ]; then
	if [ -f `brew --prefix`/Library/Contributions/brew_bash_completion.sh ]; then
	  . `brew --prefix`/Library/Contributions/brew_bash_completion.sh
	fi
fi

_autojump() 
{
        local cur
        cur=${COMP_WORDS[*]:1}
        while read i
        do
            COMPREPLY=("${COMPREPLY[@]}" "${i}")
        done  < <(autojump --bash --completion $cur)
}
complete -F _autojump j
AUTOJUMP='{ (autojump -a "$(pwd -P)"&)>/dev/null 2>>${HOME}/.autojump_errors;} 2>/dev/null'
if [[ ! $PROMPT_COMMAND =~ autojump ]]; then
  export PROMPT_COMMAND="${PROMPT_COMMAND:-:} && $AUTOJUMP"
fi 
alias jumpstat="autojump --stat"
function j { new_path="$(autojump $@)";if [ -n "$new_path" ]; then echo -e "\\033[31m${new_path}\\033[0m"; cd "$new_path";fi }
