export NICE_HOSTNAME=`hostname -f`
export SHORT_HOST=`hostname -s`

[[ -s ~/.bash_local ]] && source ~/.bash_local

source ~/.config/bash/exports
source ~/.config/bash/colors
source ~/.config/git/gitrc
source ~/.config/bash/aliases
source ~/.config/bash/prompt
source ~/.config/bash/save-directory

test -f ~/.git-completion.bash && . $_

[[ -s /etc/bash_completion ]] && source /etc/bash_completion

# readline settings
bind "set completion-ignore-case on"
bind "set bell-style none" # No bell, because it's damn annoying
bind "set show-all-if-ambiguous On" # this allows you to automatically show completion without double tab-ing

shopt -s checkwinsize
shopt -s histappend
shopt -s globstar 2>/dev/null # Bash 4 and above only

# RVM - Ruby Version Manager
[[ -s ~/.rvm/scripts/rvm ]] && source ~/.rvm/scripts/rvm
[[ -r $rvm_path/scripts/completion ]] && source $rvm_path/scripts/completion

if [ $SYSTEM_NAME = 'Linux' ]; then
  # NVM - Node Version Manager
  [[ -s ~/.nvm/nvm.sh ]] && source ~/.nvm/nvm.sh
fi

if [ $SYSTEM_NAME = 'Darwin' ]; then
  # boot2docker 1.4
  [[ -s $(brew --prefix)/bin/boot2docker ]] && $(boot2docker shellinit 2>/dev/null)
  . ~/.config/bash/terminal
  # brew install nvm (0.22.2)
  if [ -f $(brew --prefix nvm)/nvm.sh ]; then
    source $(brew --prefix nvm)/nvm.sh
  elif [ -f ~/.nvm/nvm.sh ]; then
    source ~/.nvm/nvm.sh
    #export NVM_NODEJS_ORG_MIRROR="https://iojs.org/dist/"
    #export NVM_NODE_PREFIX="iojs"
  fi
  # brew install bash-completion
  [[ -s $(brew --prefix)/etc/bash_completion ]] && source $(brew --prefix)/etc/bash_completion
fi

complete -C ~/.config/ruby/rake-completion.rb -o default rake

INIT_AUTOJUMP=~/.config/bash/autojump/autojump.bash
[[ -s ${INIT_AUTOJUMP} ]] && . ${INIT_AUTOJUMP}

if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi
