#!/usr/bin/env bash

export SYSTEM_NAME=`uname -s`

if [ $SYSTEM_NAME = 'Darwin' ]; then
  export CDPATH='.:~:~/src:~/src/oss'
  # needed by NVM as location to install Node.js versions
  export NVM_DIR=~/.nvm
  export EDITOR='atom --wait'
  export GEM_OPEN_EDITOR='atom'
  export ATOM_REPOS_HOME=~/src/oss
  # need by Rust racer to perform auto-completion lookups
  export RUST_SRC_PATH=~/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src
else
  export EDITOR='vim'
fi

export BYOBU_PREFIX=/usr/local

# needed to support Golang's package system
[[ -s ~/go ]] && export GOPATH=~/go && export PATH="$GOPATH/bin:$PATH"
[[ -s /usr/local/opt/go/libexec/bin ]] && export PATH="/usr/local/opt/go/libexec/bin:$PATH"
[[ -s ~/bin ]] && export PATH="~/bin:$PATH"
[[ -s /usr/local/sbin ]] && export PATH="/usr/local/sbin:$PATH"

# add play framework to PATH
test -d ~/etc/play-2.2.2 && export PATH="$_:$PATH"

# https://github.com/wofr06/lesspipe
# if which lesspipe.sh > /dev/null; then
#   export LESSOPEN="|lesspipe.sh %s"
#   export LESSQUIET=1
# fi

# ruby console config
export RBENV_VERSION=2.3.1
[[ -s ~/.irbrc ]] && export IRBRC="~/.irbrc"

export GIT_EDITOR=$EDITOR
export VISUAL=$EDITOR

#export TERM=xterm-color
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='0;32'
# grep 2.9+
export GREP_COLORS="ms=00;32:mc=01;31:sl=:cx=:fn=01;34:ln=0;33:bn=32:se=36"
export CLICOLOR=1

export LESS=-R
export HISTIGNORE="&:[ ]*:exit:atom*:rm:cd:dc:npm[ ]*:gs:gco[ ]*:j[ ]*:cat:type:touch:mv:ls:la:history"

export HH_CONFIG=hicolor         # get more colors
shopt -s histappend              # append new history items to .bash_history
export HISTCONTROL=ignorespace   # leading space hides commands from history
export HISTFILESIZE=1000000      # increase history file size (default is 500)
export HISTSIZE=${HISTFILESIZE}  # increase history size (default is 500)
# if this is interactive shell, then bind hh to Ctrl-r (for Vi mode check doc)
if [[ $- =~ .*i.* ]]; then bind '"\C-r": "\C-a hh -- \C-j"'; fi
# if this is interactive shell, then bind 'kill last command' to Ctrl-x k
if [[ $- =~ .*i.* ]]; then bind '"\C-xk": "\C-a hh -k \C-j"'; fi


if ls --color -d . >/dev/null 2>&1; then
  export GNU_LS=1
  export LS_OPTIONS=--color=auto
  eval `dircolors -b ~/.dir_colors`
elif ls -G -d . >/dev/null 2>&1; then
  export BSD_LS=1
  export LS_OPTIONS=-G
  export LSCOLORS=ExFxCxDxBxegedabagacad
fi
